moj:
  server:
    basedir: /tmp/mojserver
    teamDirectory: teams
    assignmentDirectory: assignments
    libDirectory: lib
    gitrepository: ssh://git@bitbucket.org/first8/practice-assignments.git
    branch: origin/master
    threads: 20
    timeout: 1
    compiler:
      workDir: ./work
      outputDir: ./classes
      inheritClassPath: no
      classPath:
        - junit/junit/4.12/junit-4.12.jar
      
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/tmp/mojserver/db/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver     
    initialize: false         
  thymeleaf:
    mode: HTML
server.session.timeout: 36000
security.basic.enabled: false


mybatis.mapper-locations: persistence/*
logging.file: mojserver.log
logging.level.nl.moj.server: DEBUG
logging.level.nl.moj.server.persistence.TeamMapper: INFO
logging.level.nl.moj.server.persistence.ResultMapper: INFO
logging.level.org.springframework.integration.file.FileReadingMessageSource: FATAL
...