moj:
  server:
    assignment-repo: /tmp/assignments
    performance-validation: true
    languages:
      java-versions:
        - version: 8
          name: Java 8
          compiler: /usr/bin/javac
          runtime: /usr/bin/java
        - version: 10
          name: Java 10
          compiler: /usr/bin/javac
          runtime: /usr/bin/java
    directories:
      team-directory: teams
      lib-directory: lib
      sound-directory: sounds
      javadoc-directory: javadoc
      base-directory: moj-data
    limits:
      compile-timeout: PT30S
      compile-output-limits:
        max-feedback-lines: 1000
        max-chars: 100000
        max-line-len: 1000
        line-truncated-message: "...{truncated}"
        output-trunc-message: "...{output truncated}"
        timeout-message: "...{terminated: compile time expired}"
      test-timeout: PT30S
      test-output-limits:
        max-feedback-lines: 1000
        max-chars: 100000
        max-line-len: 1000
        line-truncated-message: "...{truncated}"
        output-trunc-message: "...{output truncated}"
        timeout-message: "...{terminated: test time expired}"
    runtime:
      game-threads: 20
    competition:
      uuid: 77eff9b5-46cb-4420-bddf-fea52716fc6a
      success-bonus: 400

keycloak:
  auth-server-url: http://localhost:8888
  realm: moj
  resource: moj
  public-client: true
  principal-attribute: subject
  use-resource-role-mappings: true

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/opt/mojserver/db/test?close_on_exit=false
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  thymeleaf:
    mode: HTML
  flyway:
    enabled: true
    baseline-on-migrate: true
  web:
    resources:
      static-locations: classpath:/bootstrap/sounds/,classpath:/static/
  artemis:
    embedded:
      enabled: true
      queues: compile_request,compile_response,test_request,test_response,submit_request,submit_response
    mode: embedded
    broker-url: vm://0
    user: admin
    password: admin
server:
  forward-headers-strategy: native

logging:
  level:
    nl.moj.server: debug
    org.keycloak: error
    "org.apache.activemq.audit.base": error
    "org.apache.activemq.audit.message": error