---

moj:
  server:
    compiler:
      workDir: ./work
      outputDir: ./classes
      inheritClassPath: no
      classPath:
        - junit/junit/4.12/junit-4.12.jar
        
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver              
  thymeleaf:
    mode: HTML
    
security.basic.enabled: false

mybatis.mapper-locations: persistence/mapper.xml

logging.level.nl.moj.server.persistence.TeamMapper: DEBUG
logging.level.org.springframework.integration.file.FileReadingMessageSource: FATAL
...