moj:
  server:
    mode: worker
    controller-endpoint: ${CONTROLLER_URI}
spring:
  artemis:
    embedded:
      enabled: false
    mode: native
    broker-url: ${CONTROLLER_BROKER_URI}?consumerWindowSize=0
  jms:
    listener:
      concurrency: 1
      max-concurrency: 1
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration