moj:
  server:
    javaExecutable: /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/bin
    directories:
      baseDirectory: /opt/mojserver
      teamDirectory: teams
      assignmentDirectory: assignments
      libDirectory: lib
      soundDirectory: sounds
      javaDocDirectory: javadoc
    assignments:
      repos:
        -
          name: "practice-assignments"
          url: "ssh://git@bitbucket.org/first8/practice-assignments.git"
          branch: "origin/master"
        -
          name: "2017-assignments"
          url: "ssh://git@bitbucket.org/first8/2017-assignments.git"
          branch: "origin/new_layout"
    threads: 20
    timeout: 5
    limits:
      unitTestTimeoutSeconds: 4
      unitTestOutput:
        maxFeedbackLines: 1000
        maxChars: 100000
        maxLineLen: 1000
        lineTruncatedMessage: "...{truncated}"
        outputTruncMessage: "...{output truncated}"
        testTimoutTermination: "...{terminated: test time expired}"

    competition:
       bonusForSuccessfulSubmission: 400    


spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/opt/mojserver/db/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver     
    initialize: true
  thymeleaf:
    mode: HTML
  flyway:
    baseline-on-migrate: true
server.session.timeout: 36000
security.basic.enabled: false

logging.file: mojserver.log
#logging.level.nl.moj.server: DEBUG
#logging.level.nl.moj.server.persistence: INFO
#logging.level.nl.moj.server.persistence.TeamMapper: INFO
#logging.level.nl.moj.server.persistence.ResultMapper: INFO
#logging.level.org.springframework.integration.file.FileReadingMessageSource: FATAL
...