moj:
  server:
    mode: worker
    controller-endpoint: ${CONTROLLER_URI}
spring:
  artemis:
    embedded:
      enabled: false
    mode: native
    broker-url: ${CONTROLLER_BROKER_URI}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  main:
    web-application-type: none