moj:
  server:
    mode: controller
    data-directory: /data
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${OIDC_ISSUER_URI}
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}