moj:
  server:
    assignment-repo: /tmp/assignments
    languages:
      java-versions:
      - version: 8
        name: Java 8
        compiler: /usr/bin/javac
        runtime: /usr/bin/java
      - version: 10
        name: Java 10
        compiler: /usr/bin/javac
        runtime: /usr/bin/java
    directories:
      team-directory: teams
      lib-directory: lib
      sound-directory: sounds
      javadoc-directory: javadoc
      base-directory: moj-data
    limits:
      compile-timeout: PT4S
      compile-output-limits:
        max-feedback-lines: 1000
        max-chars: 100000
        max-line-len: 1000
        line-truncated-message: "...{truncated}"
        output-trunc-message: "...{output truncated}"
        timeout-message: "...{terminated: compile time expired}"
      test-timeout: PT4S
      test-output-limits:
        max-feedback-lines: 1000
        max-chars: 100000
        max-line-len: 1000
        line-truncated-message: "...{truncated}"
        output-trunc-message: "...{output truncated}"
        timeout-message: "...{terminated: test time expired}"
    runtime:
      game-threads: 10
    competition:
      uuid: 77eff9b5-46cb-4420-bddf-fea52716fc6a
      success-bonus: 400

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/opt/mojserver/db/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  thymeleaf:
    mode: HTML
  flyway:
    enabled: true
    baseline-on-migrate: true
#  jpa:
#    generate-ddl: true

logging.level.nl.moj.server: DEBUG
logging.level.nl.moj.server.persistence: INFO
logging.level.nl.moj.server.persistence.TeamMapper: INFO
logging.level.nl.moj.server.persistence.ResultMapper: INFO
logging.level.org.springframework.integration.file.FileReadingMessageSource: FATAL
