{{- if .Values.global.postgres.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controller.fullname" . }}-credentials
  labels:
    {{- include "controller.labels" . | nindent 4 }}
type: Opaque
data:
  db_username: {{ .Values.global.controller.database.username | default "controller" | b64enc }}
  db_password: {{ .Values.global.controller.database.password | default "controller" | b64enc }}
  {{- end -}}