apiVersion: v1
kind: Service
metadata:
  name: {{ include "controller.service.name" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "controller.service.port" . }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ include "controller.service.queuePort" . }}
      targetPort: 61616
      protocol: TCP
      name: queue
  selector:
    {{- include "controller.selectorLabels" . | nindent 4 }}
