apiVersion: v1
kind: Service
metadata:
  name: {{ include "controller.service.name" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 61616
      targetPort: 61616
      protocol: TCP
      name: queue
  selector:
    {{- include "controller.selectorLabels" . | nindent 4 }}
