apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: controller
        app.kubernetes.io/component: service
    spec:
      imagePullSecrets:
        - name: docker.first8.nl
      containers:
        - name: moj
          imagePullPolicy: Always
          image: docker.first8.nl/moj/moj-controller:17
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          env:
            - name: "OIDC_ISSUER_URI"
              value: "http://auth/realms/moj"
          ports:
            - containerPort: 8080
# health checks