apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: controller
spec:
  selector:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: controller
  ports:
    - port: 80
      targetPort: 8080
