version: '2.4'
services:
  moj:
    image: moj-single:17
    cpus: 3
    mem_reservation: 2g
    mem_limit: 4g
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      OIDC_ISSUER_URI: http://host.docker.internal:8888/realms/moj
#    volumes:
#      - "./data:/data"