version: '2.4'
services:
  auth:
    image: quay.io/keycloak/keycloak:21.1
    cpus: 1
    mem_reservation: 512m
    mem_limit: 1g
    restart: unless-stopped
    ports:
      - "8888:8080"
    command:
      - "start-dev"
      - "--import-realm"
      - "--hostname=host.docker.internal"
      - "--hostname-strict-https=false"
      - "--http-enabled=true"
    environment:
      KEYCLOAK_ADMIN: "keycloak"
      KEYCLOAK_ADMIN_PASSWORD: "keycloak"
      KC_DB: postgres
      KC_DB_USERNAME: iam
      KC_DB_PASSWORD: iam
      KC_DB_URL: "jdbc:postgresql://postgres:5432/iam"
    volumes:
      - "./realms:/opt/keycloak/data/import"