{{- if $.Values.global.postgres.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-credentials
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.admin.username | default "postgres" | b64enc }}
  password: {{ .Values.admin.password | default "postgres" | b64enc }}
  {{- if $.Values.global.postgres.enabled }}
  databases: {{ include "postgres.datatbases" . | b64enc }}
  {{- end }}
{{- end }}