{{- if $.Values.global.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.service.name" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "postgres.service.port" . }}
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
{{- end }}