version: '2.4'
services:
  moj:
    image: registry.cloud.bliep.net/moj/moj-game-server:latest
    cpus: 3
    mem_reservation: 2g
    mem_limit: 4g
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      VIRTUAL_HOST: "game.moj.first8.nl"
      LETSENCRYPT_HOST: "game.moj.first8.nl"
      LETSENCRYPT_EMAIL: "sysadmin@first8.nl"
      LETSENCRYPT_TEST: "true"
    volumes:
      - "./data:/data"
    networks:
      - webproxy

networks:
  webproxy: