apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iam.fullname" . }}-config
  labels:
      {{- include "iam.labels" . | nindent 4 }}
data:
{{- $redirectUri := (include "iam.redirectUri" .) }}
{{ (.Files.Glob "realms/*").AsConfig | replace "${redirectUri}" $redirectUri | indent 2 }}
