{{- if .Values.global.iam.ingress.enabled -}}
{{- $svcName := include "iam.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "iam.fullname" . }}
  labels:
    {{- include "iam.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.global.iam.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.iam.ingress.host }}
      secretName: {{ include "iam.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.global.iam.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: 80
{{- end }}
