apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iam.fullname" . }}-credentials
  labels:
    {{- include "iam.labels" . | nindent 4 }}
type: Opaque
data:
  admin_username: {{ .Values.admin.username | default "keycloak" | b64enc }}
  admin_password: {{ .Values.admin.password | default "keycloak" | b64enc }}
  db_username: {{ .Values.global.postgres.databases.iam.username | default "keycloak" | b64enc }}
  db_password: {{ .Values.global.postgres.databases.iam.password | default "keycloak" | b64enc }}