apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgres
          imagePullPolicy: Always
          image: docker.io/postgres:15
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: moj-credentials
                  key: db-admin-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: moj-credentials
                  key: db-admin-password
            - name: POSTGRES_MULTIPLE_DATABASES
              valueFrom:
                configMapKeyRef:
                  name: moj-environment
                  key: databases
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-scripts
      volumes:
        - name: postgres-scripts
          configMap:
            name: postgres-scripts